name: Airbnb_TP_Fouad-poo
recipe: lamp
config:
  php: '8.2'
  webroot: ./public
  xdebug: 'develop,debug'
services:
  appserver:
    config:
      php: ./.lando.config/php.ini
  database:
    portforward: 3308
    creds:
      user: admin   
      password: admin
      database: airbnb